const faculty = [
  {
    title: "Sarah Ita Levitan",
    description: "Faculty Advisor",
    major: "Assistant Professor of Computer Science",
    imageUrl: "/images/officers/Sarah-Levitan.jpg",
    linkedin: "https://www.linkedin.com/in/sarah-ita-levitan-7b1b3b1b/",
    github: "",
    email: "hunterwics@gmail.com",
  },
];

const eboard = [
  {
    title: "Ynalois Pangilinan",
    description: "President",
    major: "Computer Science",
    imageUrl: "/images/officers/ynalois-pangilinan2.jpg",
    linkedin: "https://www.linkedin.com/in/ynalois-pangilinan",
    github: "",
    email: "ynaloispangilinan@gmail.com",
  },
  {
    title: "Makiya Laurenza",
    description: "Vice President",
    major: "Computer Science",
    imageUrl: "/images/officers/makiya-l.jpg",
    linkedin: "https://www.linkedin.com/in/makiya-laurenza/",
    github: "",
    email: "makiyalaurenza1@gmail.com",
  },
  {
    title: "Lena Ngo",
    description: "Secretary",
    major: "Computer Science",
    imageUrl: "/images/officers/Lena-ngo.jpeg",
    linkedin: "https://www.linkedin.com/in/lena-ngo-08098b259/",
    github: "",
    email: "lenango14@gmail.com",
  },
  {
    title: "Monae White",
    description: "Treasurer",
    major: "Computer Science",
    imageUrl: "/images/officers/Monae-White.jpg",
    linkedin: "https://www.linkedin.com/in/monae-white",
    github: "",
    email: "monae.white78@myhunter.cuny.edu",
  },
];

const team = [
  {
    title: "Kripamoye Biswas",
    description: "Social Media Manager",
    major: "Computer Science & Math Major",
    imageUrl: "/images/officers/Kripamoye-Biswas.png",
    linkedin: "https://www.linkedin.com/in/kripamoyebiswas",
    github: "",
    email: "biswaskripamoye@gmail.com",
  },
  {
    title: "Angela Zhang",
    description: "Social Media Manager",
    major: "Computer Science",
    imageUrl: "/images/officers/angela-z.jpeg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Sanjida Fairuse",
    description: "Community Officer",
    major: "Computer Science",
    imageUrl: "/images/officers/sanjida-f.jpeg",
    linkedin: "https://www.linkedin.com/in/sanjida-f",
    github: "",
    email: "sanjida.fairuse58@myhunter.cuny.edu",
  },
  {
    title: "Keoma Blake",
    description: "Community Officer",
    major: "Computer Science",
    imageUrl: "/images/officers/keoma-blake.jpeg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Michelle Rivera Perez",
    description: "Social Media Manager",
    major: "Computer Science",
    imageUrl: "/images/officers/michelle-r.jpg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Riya",
    description: "Graphic Designer",
    major: "Computer Science",
    imageUrl: "/images/officers/abakariyyah-ahmed.JPG", 
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Yaritza Yanez",
    description: "Graphic Designer",
    major: "Computer Science",
    imageUrl: "/images/officers/yaritza-yanez.jpeg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
];

const webMaster = [
  {
    title: "Selina Zheng",
    description: "Web Master",
    major: "Computer Science and Chinese",
    imageUrl: "/images/officers/selina-z.jpeg",
    linkedin: "",
    github: "https://github.com/SelinaZheng-LX",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Anita Prova",
    description: "Web Master",
    major: "Computer Science",
    imageUrl: "/images/officers/anita-p.jpg",
    linkedin: "https://www.linkedin.com/in/anita-prova-950322245/",
    github: "https://github.com/anitaprova",
    email: "anita.prova49@myhunter.cuny.edu",
  },
  {
    title: "Vincent Zhong",
    description: "Web Master",
    major: "Computer Science and Chinese",
    imageUrl: "/images/officers/icon-virtual.png",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
];

const workshop = [
  {
    title: "Sy'rai Pierre",
    description: "Tech Workshop Coordinator",
    major: "Computer Science",
    imageUrl: "/images/officers/syrai-pierre.png",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Marie Cari",
    description: "Tech Workshop Coordinator",
    major: "Computer Science & Math Major",
    imageUrl: "/images/officers/marie-c.jpg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Linh Le",
    description: "Tech Workshop Coordinator",
    major: "Computer Science",
    imageUrl: "/images/officers/linh-le.jpeg",
    linkedin: "",
    github: "",
    email: "hunterwics@gmail.com",
  },
  {
    title: "Allison Lee",
    description: "Tech Workshop Coordinator",
    major: "Computer Science",
    imageUrl: "/images/officers/allison-lee.jpg",
    linkedin: "https://www.linkedin.com/in/allis0nlee",
    github: "",
    email: "esera.lee093@gmail.com",
  },
];

export { faculty, eboard, team, webMaster, workshop };
